const cameraMap  = {
    "AA": "Ansco Autoset",
    "C1": "Canon Digital IXUS 700",
    "DV": "Sony HDW-700 HDTV (High Definition Television)",
    "E2": "Kodak DCS460 Electronic Still Camera",
    "E3": "Kodak DCS660 Electronic Still Camera",
    "E4": "Kodak DCS760c Electronic Still Camera",
    "HB": "Hasselblad",
    "LH": "Linhof",
    "MA": "Maurer model 220G",
    "MS": "Maurer with Xenotar 80mm f/2.8 lens",
    "N1": "Nikon D1 Electronic Still Camera",
    "N2": "Nikon D2Xs Electronic Still Camera",
    "N3": "Nikon D3 Electronic Still Camera",
    "N4": "Nikon D3X Electronic Still Camera",
    "N5": "Nikon D3S Electronic Still Camera",
    "N6": "Nikon D4 Electronic Still Camera",
    "N7": "Nikon D800E Electronic Still Camera",
    "N8": "Nikon D5 Electronic Still Camera",
    "N9": "Nikon D850 Electronic Still Camera",
    "NK": "Nikon 35mm film camera",
    "RX": "Rolleiflex",
    "SA": "Skylab Multispectral (S190A)",
    "SB": "Skylab Earth Terrain (S190B)"
  };

const filmMap = {
    "1035I": { type: "Digital media", description: "Sony HDW-700 Digital HDTV camcorder, 15x zoom lens, 1920 x 1035 interlaced" },
    "2000E": { type: "Digital media", description: "2000 x 1312 pixel CCD, RGBG imager color filter" },
    "2041": { type: "Color negative", description: "Kodak Pro PMZ 1000, color negative, process C-41, 35mm or 120mm" },
    "2106": { type: "Color negative", description: "Kodak Vericolor III, 70mm negative unperforated, process C-41" },
    "2402": { type: "Black and white", description: "Kodak Plus-X Aerographic 70mm black and white" },
    "2415": { type: "Black and white", description: "Kodak Technical Pan Film 2415 Estar AH Base, B&W positive, ASA 100" },
    "2443": { type: "Color infrared", description: "Kodak Aerochrome 2443, color IR, thin base, EA-5 process thru June 1999, E-6 process afterward" },
    "2447": { type: "Color positive", description: "Kodak Aerochrome II Duplicating Film, 70mm, process EA-5" },
    "2448": { type: "Color positive", description: "Fine Grain Aerochrome II color-reversal camera film, 70mm, process EA-5" },
    "3060E": { type: "Digital media", description: "3060 x 2036 pixel CCD, RGBG array" },
    "3072E": { type: "Digital media", description: "3072 x 2304 pixels largest option, 1/1.8\" CCD, ~7.1M pixels, Primary Color filter type" },
    "3101": { type: "Color negative", description: "Kodak, natural color negative, Ektar 100-3101, ASA 125, standard base" },
    "4256E": { type: "Digital media", description: "4256 x 2832 pixel CMOS sensor, 36.0mm x 23.9mm, total pixels: 12.87 million, Nikon FX format" },
    "4288E": { type: "Digital media", description: "4288 x 2848 pixel CMOS sensor, RGBG imager color filter" },
    "4928E": { type: "Digital media", description: "4928 x 3280 pixel CMOS sensor, 36.0mm x 23.9mm, total pixels: 16.6 million, Nikon FX format" },
    "5012": { type: "Color positive", description: "Kodak Ektachrome 100, Professional, daylight balance" },
    "5017": { type: "Color positive", description: "Kodak, natural color positive, Ektachrome, X Professional, ASA 64, standard base" },
    "5025": { type: "Color positive", description: "Kodak Ektachrome X Professional ASA 64" },
    "5026": { type: "Color negative", description: "Kodak, natural color negative, Vericolor III 5026, ASA 160, standard base" },
    "5028": { type: "Color positive", description: "Kodak, color positive,Vericolor 400 Proof (VPH),ASA 400, standard base" },
    "5030": { type: "Color negative", description: "Kodak, natural color negative, Ektapress 5030, ASA 1600,standard base" },
    "5036": { type: "Color positive", description: "Kodak, natural color positive, Ektachrome 5036,200 Professional, ASA 200, stand" },
    "5046": { type: "Color positive", description: "Kodak, natural color positive, Lumiere 100/5046, ASA 100, standard base" },
    "5048": { type: "Color positive", description: "Kodak, natural color positive, Lumiere 100x/5048, ASA 100x, standard base" },
    "5069": { type: "Color positive", description: "Kodak Elite 100S, E6 Reversal, Replaces Lumiere, Warmer in tone vs. Lumiere" },
    "5074": { type: "Color positive", description: "Kodak Ektachrome 400, Daylight" },
    "5080": { type: "Color negative", description: "Kodak Pro 400, color negative, ASA 400, 35mm" },
    "5095": { type: "Color negative", description: "Kodak, color negative, Kodacolor VRG/100, ASA 100, standard base" },
    "5096": { type: "Color negative", description: "Kodak, color negative, Gold Super 200, ASA 200, standard base" },
    "5245": { type: "Color positive", description: "Kodak EXR 500" },
    "5250": { type: "Color negative", description: "Eastman Color Negative, 35mm" },
    "5327": { type: "Color positive", description: "Kodak, natural color positive, Ektar 25 Professional, ASA 25, standard base" },
    "5568E": { type: "Digital media", description: "5568 x 3712 pixel CMOS sensor, 35.9 x 23.9 mm, total pixels: 21.33 million, Nikon FX format" },
    "5755": { type: "Color negative", description: "Portra 160NC, color negative, 35mm, ASA 160" },
    "5775": { type: "Color negative", description: "Portra 400NC, color negative, 35mm, ASA 400" },
    "5776": { type: "Color positive", description: "Portra 400VC, color negative, 35mm, ASA 400" },
    "6017": { type: "Color positive", description: "Kodak Ektachrome 64, 220 Roll Format" },
    "6048E": { type: "Digital media", description: "6048 x 4032 pixel CMOS sensor, 35.9mm x 24.0mm, total pixels: 25.72 million, Nikon FX format" },
    "6118": { type: "Color positive", description: "Kodak Ektachrome 64T, color positive, Professional Film, ASA 64" },
    "6144E": { type: "Digital media", description: "19.4 megapixel CMOS, 6144 x 3160 effective pixels, 30.7 mm x 15.8 mm (diagonal: 34.5 mm)" },
    "7360E": { type: "Digital media", description: "7360 x 4912 pixel CMOS sensor, 35.9mm x 24.0mm, total pixels: 36.8 million, Nikon FX format" },
    "8256E": { type: "Digital media", description: "8256 x 5504 pixel CMOS sensor, 35.9mm x 23.9mm, total pixels: 46.89 million, Nikon FX format" },
    "8443": { type: "Color infrared", description: "Kodak Aerochrome IR, process: EA-4, replaced by 2443" },
    "ANSCO": { type: "Color positive", description: "Anscochrome T-100 Superior, ASA 100/64, Color positive" },
    "E2424": { type: "Black and white", description: "Kodak B&W infrared, no filter" },
    "E2424C": { type: "Black and white", description: "Kodak B&W infrared, 0.7-0.8 micron filter band-pass" },
    "E2424D": { type: "Black and white", description: "Kodak B&W infrared, 0.8-0.9 micron filter band-pass" },
    "E2443": { type: "Color infrared", description: "Kodak color infrared" },
    "E3414": { type: "Black and white", description: "Kodak Cadmium-enriched Hi-definition B&W Aerial film, \"minus blue\" Wratten filter" },
    "E3443": { type: "Color infrared", description: "Kodak infrared color, \"minus blue\" Wratten filter" },
    "EKTAR": { type: "Color negative", description: "Kodak Ektar 25 color negative Professional Film, ASA 25" },
    "FJ400": { type: "Color negative", description: "Fuji natural color negative, FUJI NHG, ASA 400, standard base" },
    "FJ800": { type: "Color negative", description: "Fuji color negative, 35mm, ASA 800" },
    "QX": { type: "Color infrared", description: "Kodak color infrared" },
    "QX807": { type: "Color positive", description: "SO368 film (fine-grain Ektachrome) with yellow dye layer equivalent to Wratten 2A" },
    "QX824": { type: "Color positive", description: "Kodak Ektachrome 64" },
    "QX868": { type: "Color positive", description: "Kodak, natural color positive, Ektachrome QX868(5017 emulsion), ASA 64, thin base" },
    "RS200": { type: "Color positive", description: "AGFA, natural color positive, Agfachrome 200RS Professional, ASA 200, standard" },
    "RS50": { type: "Color positive", description: "AGFA, natural color positive, Agfachrome Plus Professional, ASA 50, standard" },
    "RUSSI": { type: "Unspecified", description: "Russian film of various types" },
    "SG800": { type: "Color negative", description: "FujicolorSG800, negative, 35mm, ASA 800" },
    "SN-10": { type: "Color infrared", description: "Russian Color Infrared,2 dye layer, est. ASA 64,chlorophyl response is green" },
    "SO022": { type: "Black and white", description: "Kodak B&W infrared, no filter" },
    "SO022A": { type: "Black and white", description: "Kodak Panatomic-X B&W, 0.5-0.6 micron filter band-pass" },
    "SO022B": { type: "Black and white", description: "Kodak Panatomic-X B&W, 0.6-0.7 micron filter band-pass" },
    "SO117": { type: "Color positive", description: "Kodak, natural color positive, Ektachrome SO117, ASA 400, standard base" },
    "SO121": { type: "Color positive", description: "Kodak Ektachrome 64" },
    "SO131": { type: "Color infrared", description: "Kodak High Definition Aerochrome and Estar thin base, infrared color, \"minus blue\" Wratten filter" },
    "SO180": { type: "Color infrared", description: "Kodak Ektachrome infrared" },
    "SO217": { type: "Color positive", description: "Kodak Ektachrome with haze filter" },
    "SO242": { type: "Color positive", description: "Kodak hi resolution color" },
    "SO356": { type: "Color positive", description: "Unknown SkyLab" },
    "SO368": { type: "Color positive", description: "Kodak Ektachrome MS, equivalent to 2448 Kodak Aerochrome, ASA64, thin base, fine grain" },
    "SO489": { type: "Color positive", description: "Kodak Ektachrome, high speed, ASA 400" },
    "UNKN": { type: "Unspecified", description: "unknown" },
    "VELVI": { type: "Color positive", description: "Fuji, natural color positive, Velvia 50, CS 135-36, ASA 32, standard base" }
  };
  

module.exports = { cameraMap , filmMap };
